name: Build Executables
on:
  push:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag/Commit to Build'
        default: 'master'
env:
  HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: true
jobs:
  build-mac:
    name: Build MacOS binary
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install homebrew
      shell: bash
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Install dependencies
      shell: bash
      run: brew install gtk+ vala sdl2_mixer pkgconf libpng gettext cmake
    - name: Clone crossfire-client
      shell: bash
      run: git clone https://git.code.sf.net/p/crossfire/crossfire-client && cd crossfire-client && git checkout ${{ github.event.inputs.tag }}
    - name: Patch
      shell: bash
      run: cd crossfire-client && git apply ../patch.diff
    - name: Copy macos build script
      shell: bash
      run: cd crossfire-client && mkdir gtk-v2/macos cp ../macos-package.sh gtk-v2/macos/
    - name: Compile
      run: cd crossfire-client && mkdir build && cd build && cmake .. && make && make install
    - name: Upload DMG
      uses: actions/upload-artifact@v3
      with:
        name: Crossfire-GTK2.dmg
        path: crossfire-client/build/Crossfire-GTK2.dmg
